version: '3'
services:
  app:
    container_name: app-container
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src:/workspace
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
  web:
    container_name: web-comtainer
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 80:80
    environment:
      - APP_HOST=app
    volumes:
      - ./src:/wordspace
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: db-container
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=secret
