version: '3'
services:
  app:
    container_name: "app-container"
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src:/workspace
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
  web:
    container_name: "web-comtainer"
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 80:80
    environment:
      - APP_HOST=app
    volumes:
      - ./src:/wordspace
